name: CI/CD

on:
  push:
    branches:
      - main

env:
  MONGO_DB_HOST: ${{ secrets.MONGO_DB_HOST }}
  MONGO_DB_PORT: ${{ secrets.MONGO_DB_PORT }}
  MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
  MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
  MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  build:
    name: Build and Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and Push Web App Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/financify:latest ./web-app
          docker push $DOCKER_USERNAME/financify:latest

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd financify && docker compose down && git pull && docker compose up --build -d

      - name: Logout from DockerHub
        run: docker logout